# Generated by Django 5.0.3 on 2024-04-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(verbose_name='Site URL'),
        ),
    ]
